/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.45
 * Generated at: 2024-03-18 11:25:27 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;

public final class patientData_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <title>A Patient</title>\n");
      out.write("  <style>\n");
      out.write("    .modify-link {\n");
      out.write("        text-decoration: underline;\n");
      out.write("        color: blue;\n");
      out.write("        cursor: pointer;\n");
      out.write("        margin-bottom: 10px;\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <h2>Patient Details:</h2>\n");
      out.write("  ");
 List<String> patientData = (List<String>) request.getAttribute("patientData"); 
      out.write("\n");
      out.write("  <a href=\"/delete.jsp?data=");
      out.print( patientData.get(0) );
      out.write("\">delete</a>\n");
      out.write("  <div class=\"modify-link\" onclick=\"showModifyOptions()\">modify</div>\n");
      out.write("  <div id=\"modifyOptions\" style=\"display: none;\">\n");
      out.write("    <p>Select an option:</p>\n");
      out.write("    <ul>\n");
      out.write("        <li><a href=\"/modify.jsp?field=1&data=");
      out.print( patientData.get(0) );
      out.write("\">ID</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=2&data=");
      out.print( patientData.get(0) );
      out.write("\">BIRTHDATE</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=3&data=");
      out.print( patientData.get(0) );
      out.write("\">DEATHDATE</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=4&data=");
      out.print( patientData.get(0) );
      out.write("\">SSN</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=5&data=");
      out.print( patientData.get(0) );
      out.write("\">DRIVERS</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=6&data=");
      out.print( patientData.get(0) );
      out.write("\">PASSPORT</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=7&data=");
      out.print( patientData.get(0) );
      out.write("\">PREFIX</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=8&data=");
      out.print( patientData.get(0) );
      out.write("\">FIRST</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=9&data=");
      out.print( patientData.get(0) );
      out.write("\">LAST</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=10&data=");
      out.print( patientData.get(0) );
      out.write("\">SUFFIX</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=11&data=");
      out.print( patientData.get(0) );
      out.write("\">MAIDEN</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=12&data=");
      out.print( patientData.get(0) );
      out.write("\">MARITAL</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=13&data=");
      out.print( patientData.get(0) );
      out.write("\">RACE</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=14&data=");
      out.print( patientData.get(0) );
      out.write("\">ETHNICITY</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=15&data=");
      out.print( patientData.get(0) );
      out.write("\">GENDER</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=16&data=");
      out.print( patientData.get(0) );
      out.write("\">BIRTHPLACE</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=17&data=");
      out.print( patientData.get(0) );
      out.write("\">ADDRESS</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=18&data=");
      out.print( patientData.get(0) );
      out.write("\">CITY</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=19&data=");
      out.print( patientData.get(0) );
      out.write("\">STATE</a></li>\n");
      out.write("        <li><a href=\"/modify.jsp?field=20&data=");
      out.print( patientData.get(0) );
      out.write("\">ZIP</a></li>\n");
      out.write("    </ul>\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  \n");
      out.write("  ");
 List<String> title = (List<String>) request.getAttribute("columnNames"); 
      out.write('\n');
      out.write(' ');
      out.write(' ');
 if (patientData != null) { 
      out.write("\n");
      out.write("    ");
 for (int i = 0; i < patientData.size(); i++) { 
      out.write("\n");
      out.write("      <p>");
      out.print( title.get(i) );
      out.write(":</p>\n");
      out.write("      <p> ");
      out.print( patientData.get(i) );
      out.write("</p>\n");
      out.write("    ");
 } 
      out.write('\n');
      out.write(' ');
      out.write(' ');
 } else { 
      out.write("\n");
      out.write("    <p>No patient data available.</p>\n");
      out.write("  ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("  <script>\n");
      out.write("    function showModifyOptions() {\n");
      out.write("      var modifyOptions = document.getElementById(\"modifyOptions\");\n");
      out.write("      modifyOptions.style.display = \"block\";\n");
      out.write("    }\n");
      out.write("  </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
